// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSchoolApi.Data;

namespace ProjectSchoolApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("ProjectSchoolApi.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataNasc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNasc = "01/01/2000",
                            Nome = "José",
                            ProfessorId = 1,
                            Sobrenome = "da Silva"
                        },
                        new
                        {
                            Id = 2,
                            DataNasc = "11/12/1978",
                            Nome = "João",
                            ProfessorId = 2,
                            Sobrenome = "Beloti"
                        },
                        new
                        {
                            Id = 3,
                            DataNasc = "07/08/1986",
                            Nome = "Alex",
                            ProfessorId = 3,
                            Sobrenome = "Beluci"
                        });
                });

            modelBuilder.Entity("ProjectSchoolApi.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Alisson"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Fernando"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Paola"
                        });
                });

            modelBuilder.Entity("ProjectSchoolApi.Models.Aluno", b =>
                {
                    b.HasOne("ProjectSchoolApi.Models.Professor", "Professor")
                        .WithMany("Alunos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
